package com.example.yourcare.utils

import android.annotation.SuppressLint
import android.content.Context
import android.content.Intent
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream

object PdfHelper {

    @SuppressLint("NewApi")
    fun generateAndSharePdf(
        context: Context,
        avg: Float,
        max: Float,
        min: Float,
        freq: Float, // Add this
        status: String
    ) {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 Size
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas
        val paint = Paint()

        // 1. Header
        paint.color = android.graphics.Color.parseColor("#1D8F9B") // Ripple Teal
        paint.textSize = 24f
        paint.isFakeBoldText = true
        canvas.drawText("TremorScan Pro - Report", 50f, 80f, paint)

        // 2. Date
        paint.color = android.graphics.Color.DKGRAY
        paint.textSize = 14f
        paint.isFakeBoldText = false
        canvas.drawText("Date: ${java.time.LocalDate.now()}", 50f, 110f, paint)

        // 3. Line Separator
        paint.strokeWidth = 2f
        canvas.drawLine(50f, 130f, 545f, 130f, paint)



        // 4. Metrics
        paint.textSize = 16f
        var yPos = 180f

        fun drawRow(label: String, value: String) {
            paint.color = android.graphics.Color.BLACK
            canvas.drawText(label, 50f, yPos, paint)
            paint.color = android.graphics.Color.parseColor("#1D8F9B")
            paint.isFakeBoldText = true
            canvas.drawText(value, 400f, yPos, paint)
            paint.isFakeBoldText = false
            yPos += 40f
        }
//
//        drawRow("Average Tremor (RMS):", "%.3f rad/s".format(avg))
//        drawRow("Peak Intensity:", "%.3f rad/s".format(max))
//        drawRow("Minimum Intensity:", "%.3f rad/s".format(min))
        drawRow("Average Tremor (RMS):", "%.3f rad/s".format(avg))
        drawRow("Peak Intensity:", "%.3f rad/s".format(max))
        drawRow("Tremor Frequency:", "%.1f Hz".format(freq)) // Add this line
        drawRow("Minimum Intensity:", "%.3f rad/s".format(min))

        yPos += 20f
        paint.color = android.graphics.Color.BLACK
        paint.textSize = 18f
        paint.isFakeBoldText = true
        canvas.drawText("Assessment: $status", 50f, yPos, paint)

        // 5. Footer
        paint.color = android.graphics.Color.LTGRAY
        paint.textSize = 12f
        paint.isFakeBoldText = false
        canvas.drawText("Generated by Ripple Healthcare App", 50f, 800f, paint)

        pdfDocument.finishPage(page)

        // Save to Cache
        val docsFolder = File(context.cacheDir, "documents")
        if (!docsFolder.exists()) docsFolder.mkdirs()
        val file = File(docsFolder, "TremorReport.pdf")

        try {
            pdfDocument.writeTo(FileOutputStream(file))
            pdfDocument.close()
            sharePdf(context, file)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    private fun sharePdf(context: Context, file: File) {
        val uri: Uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.provider",
            file
        )

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }

        context.startActivity(Intent.createChooser(intent, "Share Report via"))
    }
}